name: pytorch-tlio
channels:
  - conda-forge/label/cf201901
  - numba
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=2.1.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2024.12.14=py312h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gdown=5.1.0=pyhd8ed1ab_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py312he1ff14a_4
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_1
  - h5py=3.9.0=py312h34c39bb_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=he6710b0_3
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=pyhd8ed1ab_0
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libdrm-cos6-x86_64=2.4.65=4
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libx11-common-cos6-x86_64=1.6.4=4
  - libx11-cos6-x86_64=1.6.4=4
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxi-cos6-x86_64=1.7.8=4
  - libxi-devel-cos6-x86_64=1.7.8=4
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py312h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py312h06a4308_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.8.4=py312h7900ff3_0
  - matplotlib-base=3.8.4=py312h526ad5a_0
  - mesa-libgl-cos6-x86_64=11.0.7=4
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py312h06a4308_0
  - numba=0.59.1=np1.26py3.12hcf1a7a7_g9ce83ef5c_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.3.1=hb9d3cd8_3
  - packaging=24.1=py312h06a4308_0
  - pandas=2.1.1=py312h526ad5a_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.26.2=h14c3975_0
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - pixman=0.38.0=h7b6447c_0
  - ply=3.11=py312h06a4308_1
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.11=h06a4308_1
  - portalocker=2.10.1=py312h7900ff3_0
  - protobuf=3.20.3=py312h6a678d5_0
  - pyparsing=3.0.9=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytorch=2.2.2=py3.12_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - qt-main=5.15.2=h7358343_9
  - quaternion=2023.0.3=py312hc7c0aa3_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py312h06a4308_0
  - scienceplots=2.1.1=pyhd8ed1ab_1
  - scikit-learn=1.3.0=py312h526ad5a_2
  - scipy=1.11.3=py312hc5e2394_0
  - seaborn=0.12.2=py312h06a4308_0
  - setuptools=69.5.1=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snakeviz=2.2.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py312h06a4308_0
  - tabulate=0.9.0=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.16.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312h52d8a92_0
  - termcolor=2.1.0=py312h06a4308_0
  - texlive-core=20180414=hc8d0b01_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.2.2=py312_cu118
  - torchvision=0.17.2=py312_cu118
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.2=py312h06a4308_0
  - werkzeug=3.0.3=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-fixesproto=5.0=h470a237_2
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxcursor=1.1.15=h470a237_2
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxfixes=5.0.3=h470a237_4
  - xorg-libxinerama=1.1.4=hfc679d8_0
  - xorg-libxrandr=1.5.1=0
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-randrproto=1.5.0=h470a237_1
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yacs=0.1.6=pyhd3eb1b0_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_2
  - pip:
      - asttokens==2.4.1
      - attrs==23.2.0
      - click==8.1.7
      - data==0.4
      - decorator==5.1.1
      - dm-control==1.0.19
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - etils==1.8.0
      - executing==2.0.1
      - fsspec==2024.3.1
      - funcsigs==1.0.2
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - importlib-resources==6.4.0
      - ipdb==0.13.13
      - ipython==8.23.0
      - jedi==0.19.1
      - labmaze==1.0.6
      - latex==0.7.0
      - liegroups==0.11
      - lietorch==0.2
      - lxml==5.2.1
      - matplotlib-inline==0.1.6
      - mujoco==3.1.5
      - ninja==1.11.1.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - progressbar==2.5
      - projectaria-tools==1.5.0
      - prompt-toolkit==3.0.43
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.0.0
      - pygments==2.17.2
      - pyopengl==3.1.7
      - rerun-sdk==0.15.1
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - shutilwhich==1.1.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - tempdir==0.7.1
      - tensorboardx==2.6.2.2
      - traitlets==5.14.2
      - wandb==0.17.4
      - wcwidth==0.2.13
      - wget==3.2
      - zipp==3.18.1
prefix: /mnt/kostas-graid/sw/envs/royinakj/anaconda3/envs/pytorch-tlio
